import { SecurityEvent, SecurityAlert, DetectionRule, BlockedIp } from '../types/security';

const NOW = Date.now();
const minutesAgo = (mins: number) => new Date(NOW - mins * 60 * 1000).toISOString();
const hoursAgo = (hrs: number) => new Date(NOW - hrs * 3600 * 1000).toISOString();

export const INITIAL_RULES: DetectionRule[] = [
  {
    id: 'rule-brute-force',
    name: 'High-Frequency Brute Force Detection',
    description: 'Triggers when 5 or more failed login attempts occur within 5 minutes for a specific IP or username.',
    severity: 'critical',
    enabled: true,
    threshold: 5,
    windowMinutes: 5,
    category: 'authentication',
    autoAction: 'block_ip'
  },
  {
    id: 'rule-impossible-travel',
    name: 'Impossible Geolocation Velocity',
    description: 'Detects logins from geographically distant locations within an impossible physical transit timeframe (>800 km/h).',
    severity: 'high',
    enabled: true,
    threshold: 1,
    windowMinutes: 60,
    category: 'geography',
    autoAction: 'alert_only'
  },
  {
    id: 'rule-credential-stuffing',
    name: 'Distributed Credential Stuffing',
    description: 'Flags single IP attempting authentication across 4 or more distinct usernames within 10 minutes.',
    severity: 'high',
    enabled: true,
    threshold: 4,
    windowMinutes: 10,
    category: 'authentication',
    autoAction: 'block_ip'
  },
  {
    id: 'rule-privilege-escalation',
    name: 'Unauthorized Administrative Endpoint Probe',
    description: 'Non-privileged authenticated account requesting /admin/roles, /api/internal/exec or sudo privileges.',
    severity: 'critical',
    enabled: true,
    threshold: 1,
    windowMinutes: 15,
    category: 'authorization',
    autoAction: 'revoke_session'
  },
  {
    id: 'rule-mfa-fatigue',
    name: 'MFA Push Fatigue / Repeated Denial',
    description: '3 consecutive MFA prompt rejections or timeouts followed by subsequent login bursts.',
    severity: 'medium',
    enabled: true,
    threshold: 3,
    windowMinutes: 10,
    category: 'authentication',
    autoAction: 'alert_only'
  },
  {
    id: 'rule-suspicious-user-agent',
    name: 'Malicious / Automated Scanner User-Agent',
    description: 'Requests carrying known reconnaissance or attack tool signatures (sqlmap, nmap, nikto, masscan).',
    severity: 'medium',
    enabled: true,
    threshold: 2,
    windowMinutes: 10,
    category: 'network',
    autoAction: 'block_ip'
  }
];

export const INITIAL_BLOCKED_IPS: BlockedIp[] = [
  {
    ip: '185.220.101.45',
    reason: 'Automated SSH & Web Admin Brute-Force Botnet',
    blockedAt: hoursAgo(6),
    country: 'Russia',
    city: 'Moscow',
    autoBlocked: true,
    riskScore: 96
  },
  {
    ip: '194.26.29.112',
    reason: 'High-frequency credential stuffing against customer portal',
    blockedAt: hoursAgo(2),
    country: 'Netherlands',
    city: 'Amsterdam',
    autoBlocked: true,
    riskScore: 92
  },
  {
    ip: '45.148.10.77',
    reason: 'Nikto vulnerability scanner probe targeting /api/v1/debug',
    blockedAt: hoursAgo(14),
    country: 'Lithuania',
    city: 'Vilnius',
    autoBlocked: false,
    riskScore: 84
  }
];

export const INITIAL_EVENTS: SecurityEvent[] = [
  {
    id: 'evt-101',
    timestamp: minutesAgo(2),
    type: 'login_failed',
    severity: 'high',
    username: 'admin',
    ip: '194.26.29.112',
    location: { country: 'Netherlands', countryCode: 'NL', city: 'Amsterdam', lat: 52.3676, lng: 4.9041 },
    device: { browser: 'Python-Requests/2.31', os: 'Linux', userAgent: 'python-requests/2.31.0', isVpnOrTor: true },
    status: 'blocked',
    details: 'Failed authentication attempt #7 for superuser account using wordlist payload.',
    mitreTechnique: 'T1110.001 - Password Guessing',
    endpoint: '/api/v1/auth/login',
    metadata: { attemptCount: 7, httpStatus: 401, latencyMs: 14 }
  },
  {
    id: 'evt-102',
    timestamp: minutesAgo(3),
    type: 'login_failed',
    severity: 'high',
    username: 'admin',
    ip: '194.26.29.112',
    location: { country: 'Netherlands', countryCode: 'NL', city: 'Amsterdam', lat: 52.3676, lng: 4.9041 },
    device: { browser: 'Python-Requests/2.31', os: 'Linux', userAgent: 'python-requests/2.31.0', isVpnOrTor: true },
    status: 'flagged',
    details: 'Failed authentication attempt #6 with bad password hash.',
    mitreTechnique: 'T1110.001 - Password Guessing',
    endpoint: '/api/v1/auth/login',
    metadata: { attemptCount: 6, httpStatus: 401, latencyMs: 18 }
  },
  {
    id: 'evt-103',
    timestamp: minutesAgo(5),
    type: 'login_success',
    severity: 'info',
    username: 'alex.turner@company.internal',
    ip: '12.180.44.19',
    location: { country: 'United States', countryCode: 'US', city: 'Seattle', lat: 47.6062, lng: -122.3321 },
    device: { browser: 'Chrome 122.0', os: 'macOS 14.3', userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)', isVpnOrTor: false },
    status: 'allowed',
    details: 'Valid OAuth 2.0 PKCE session established with hardware security key (FIDO2).',
    endpoint: '/api/v1/auth/callback',
    metadata: { authFactor: 'FIDO2_WEBAUTHN', sessionTtlHours: 12 }
  },
  {
    id: 'evt-104',
    timestamp: minutesAgo(9),
    type: 'impossible_travel',
    severity: 'critical',
    username: 'maria.gonzalez@company.internal',
    ip: '103.249.23.4',
    location: { country: 'Singapore', countryCode: 'SG', city: 'Singapore', lat: 1.3521, lng: 103.8198 },
    device: { browser: 'Firefox 123.0', os: 'Windows 11', userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0)', isVpnOrTor: false },
    status: 'flagged',
    details: 'Geographical anomaly: Successful login in Singapore just 18 minutes after prior authenticated activity in Austin, TX (Distance: ~15,500 km).',
    mitreTechnique: 'T1078.004 - Cloud Valid Accounts',
    endpoint: '/api/v1/auth/login',
    metadata: { priorLocation: 'Austin, US', calculatedSpeedKmH: 51600, previousTimestamp: minutesAgo(27) }
  },
  {
    id: 'evt-105',
    timestamp: minutesAgo(12),
    type: 'privilege_escalation',
    severity: 'critical',
    username: 'contractor_temp04',
    ip: '82.165.197.1',
    location: { country: 'Germany', countryCode: 'DE', city: 'Frankfurt', lat: 50.1109, lng: 8.6821 },
    device: { browser: 'Curl/8.4.0', os: 'Linux', userAgent: 'curl/8.4.0', isVpnOrTor: true },
    status: 'flagged',
    details: 'Unauthorized invocation of restricted administrative endpoint /api/v1/system/grant-superuser.',
    mitreTechnique: 'T1068 - Exploitation for Privilege Escalation',
    endpoint: '/api/v1/system/grant-superuser',
    metadata: { requiredRole: 'super_admin', actualRole: 'read_only_contractor', httpStatus: 403 }
  },
  {
    id: 'evt-106',
    timestamp: minutesAgo(18),
    type: 'mfa_denied',
    severity: 'medium',
    username: 'david.kim@company.internal',
    ip: '185.191.171.12',
    location: { country: 'United Kingdom', countryCode: 'GB', city: 'London', lat: 51.5074, lng: -0.1278 },
    device: { browser: 'Mobile Safari 17.2', os: 'iOS 17', userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2)', isVpnOrTor: false },
    status: 'flagged',
    details: 'User rejected mobile push MFA notification: Reported as unrecognized authentication prompt.',
    mitreTechnique: 'T1621 - Multi-Factor Authentication Request Generation',
    endpoint: '/api/v1/mfa/push/verify',
    metadata: { pushAttempt: 2, userAction: 'EXPLICIT_REJECT' }
  },
  {
    id: 'evt-107',
    timestamp: minutesAgo(25),
    type: 'login_success',
    severity: 'info',
    username: 'sarah.engineer@company.internal',
    ip: '198.51.100.42',
    location: { country: 'Canada', countryCode: 'CA', city: 'Toronto', lat: 43.6532, lng: -79.3832 },
    device: { browser: 'Edge 121.0', os: 'Windows 11', userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; Edg/121.0)', isVpnOrTor: false },
    status: 'allowed',
    details: 'Standard single-sign-on login verified with corporate Identity Provider.',
    endpoint: '/api/v1/auth/saml/acs',
    metadata: { idp: 'Okta Enterprise', mfaPassed: true }
  },
  {
    id: 'evt-108',
    timestamp: minutesAgo(35),
    type: 'login_failed',
    severity: 'low',
    username: 'sarah.engineer@company.internal',
    ip: '198.51.100.42',
    location: { country: 'Canada', countryCode: 'CA', city: 'Toronto', lat: 43.6532, lng: -79.3832 },
    device: { browser: 'Edge 121.0', os: 'Windows 11', userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; Edg/121.0)', isVpnOrTor: false },
    status: 'allowed',
    details: 'Expired session token or typo in password; succeeded on subsequent retry.',
    endpoint: '/api/v1/auth/login',
    metadata: { reason: 'INVALID_CREDENTIALS', retryCount: 1 }
  },
  {
    id: 'evt-109',
    timestamp: minutesAgo(42),
    type: 'port_scan',
    severity: 'medium',
    username: 'anonymous',
    ip: '45.148.10.77',
    location: { country: 'Lithuania', countryCode: 'LT', city: 'Vilnius', lat: 54.6872, lng: 25.2797 },
    device: { browser: 'Nikto/2.1.6', os: 'Unknown', userAgent: 'Mozilla/5.00 (Nikto/2.1.6)', isVpnOrTor: true },
    status: 'blocked',
    details: 'Automated vulnerability scanner probed 48 common administrative paths in 12 seconds.',
    mitreTechnique: 'T1595.002 - Vulnerability Scanning',
    endpoint: '/.env, /admin/phpmyadmin, /api/internal/debug',
    metadata: { requestsPerSec: 4.2, probedEndpoints: 48 }
  },
  {
    id: 'evt-110',
    timestamp: minutesAgo(55),
    type: 'login_success',
    severity: 'info',
    username: 'service_account_k8s_deploy',
    ip: '10.0.12.8',
    location: { country: 'United States', countryCode: 'US', city: 'Oregon', lat: 45.5152, lng: -122.6784 },
    device: { browser: 'Go-http-client/2.0', os: 'Linux', userAgent: 'Go-http-client/2.0', isVpnOrTor: false },
    status: 'allowed',
    details: 'Service account mTLS certificate handshake validated for deployment orchestrator.',
    endpoint: '/api/v1/cluster/sync',
    metadata: { certFingerprint: 'SHA256:d9b28a9...', scope: 'deploy:write' }
  },
  {
    id: 'evt-111',
    timestamp: hoursAgo(1.5),
    type: 'login_failed',
    severity: 'high',
    username: 'root',
    ip: '185.220.101.45',
    location: { country: 'Russia', countryCode: 'RU', city: 'Moscow', lat: 55.7558, lng: 37.6173 },
    device: { browser: 'SSH-2.0-OpenSSH_8.2p1', os: 'Linux', userAgent: 'SSH-2.0-OpenSSH_8.2p1', isVpnOrTor: true },
    status: 'blocked',
    details: 'Brute-force SSH attack targeted privileged root account. Dropped at perimeter edge firewall.',
    mitreTechnique: 'T1110.003 - Password Spraying',
    endpoint: 'ssh://edge-gw-01.company.internal:22',
    metadata: { port: 22, attempts: 24 }
  },
  {
    id: 'evt-112',
    timestamp: hoursAgo(2),
    type: 'password_spray',
    severity: 'high',
    username: 'jennifer.ops@company.internal',
    ip: '185.220.101.45',
    location: { country: 'Russia', countryCode: 'RU', city: 'Moscow', lat: 55.7558, lng: 37.6173 },
    device: { browser: 'Python-Requests/2.28', os: 'Linux', userAgent: 'python-requests/2.28.1', isVpnOrTor: true },
    status: 'blocked',
    details: 'Low-and-slow credential spraying against active corporate emails using common seasonal passwords.',
    mitreTechnique: 'T1110.003 - Password Spraying',
    endpoint: '/api/v1/auth/login',
    metadata: { sprayRound: 3, targetsAttempted: 14 }
  },
  {
    id: 'evt-113',
    timestamp: hoursAgo(3.2),
    type: 'token_leak',
    severity: 'critical',
    username: 'devops_ci_runner',
    ip: '172.56.21.90',
    location: { country: 'United States', countryCode: 'US', city: 'Chicago', lat: 41.8781, lng: -87.6298 },
    device: { browser: 'GitLab-Runner/16.7', os: 'Linux', userAgent: 'GitLab-Runner/16.7.0', isVpnOrTor: false },
    status: 'flagged',
    details: 'Revoked API secret token detected in publicly accessible build artifact pipeline.',
    mitreTechnique: 'T1552.001 - Credentials In Files',
    endpoint: '/api/v1/builds/artifacts/download',
    metadata: { keyPrefix: 'sec_live_99a8b1...', revokedImmediately: true }
  },
  {
    id: 'evt-114',
    timestamp: hoursAgo(4),
    type: 'login_success',
    username: 'david.kim@company.internal',
    severity: 'info',
    ip: '185.191.171.12',
    location: { country: 'United Kingdom', countryCode: 'GB', city: 'London', lat: 51.5074, lng: -0.1278 },
    device: { browser: 'Chrome 122.0', os: 'macOS 14.2', userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)', isVpnOrTor: false },
    status: 'allowed',
    details: 'Successful corporate intranet authentication after secondary biometric challenge.',
    endpoint: '/api/v1/auth/login',
    metadata: { authFactor: 'WEBAUTHN_BIOMETRIC' }
  },
  {
    id: 'evt-115',
    timestamp: hoursAgo(5.5),
    type: 'login_success',
    severity: 'info',
    username: 'maria.gonzalez@company.internal',
    ip: '24.28.102.15',
    location: { country: 'United States', countryCode: 'US', city: 'Austin', lat: 30.2672, lng: -97.7431 },
    device: { browser: 'Firefox 123.0', os: 'macOS 14.3', userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15)', isVpnOrTor: false },
    status: 'allowed',
    details: 'Standard verified login from corporate office IP space.',
    endpoint: '/api/v1/auth/login',
    metadata: { networkType: 'Corporate_Wifi_Secure' }
  },
  {
    id: 'evt-116',
    timestamp: hoursAgo(7.2),
    type: 'suspicious_geo',
    severity: 'medium',
    username: 'brian.finance@company.internal',
    ip: '177.54.144.10',
    location: { country: 'Brazil', countryCode: 'BR', city: 'São Paulo', lat: -23.5505, lng: -46.6333 },
    device: { browser: 'Chrome 121.0', os: 'Android 14', userAgent: 'Mozilla/5.0 (Linux; Android 14)', isVpnOrTor: false },
    status: 'flagged',
    details: 'First-time authentication from South America for an account with domestic policy requirement.',
    mitreTechnique: 'T1078.004 - Cloud Accounts',
    endpoint: '/api/v1/auth/login',
    metadata: { expectedCountry: 'US', actualCountry: 'BR' }
  },
  {
    id: 'evt-117',
    timestamp: hoursAgo(9),
    type: 'login_success',
    severity: 'info',
    username: 'brian.finance@company.internal',
    ip: '177.54.144.10',
    location: { country: 'Brazil', countryCode: 'BR', city: 'São Paulo', lat: -23.5505, lng: -46.6333 },
    device: { browser: 'Chrome 121.0', os: 'Android 14', userAgent: 'Mozilla/5.0 (Linux; Android 14)', isVpnOrTor: false },
    status: 'allowed',
    details: 'Manager-approved international travel exception validated with step-up hardware token.',
    endpoint: '/api/v1/auth/step-up',
    metadata: { travelApprovalTicket: 'SEC-89104' }
  },
  {
    id: 'evt-118',
    timestamp: hoursAgo(11),
    type: 'login_failed',
    severity: 'medium',
    username: 'support_lead',
    ip: '109.201.152.12',
    location: { country: 'France', countryCode: 'FR', city: 'Paris', lat: 48.8566, lng: 2.3522 },
    device: { browser: 'Safari 17.0', os: 'macOS 14.1', userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)', isVpnOrTor: false },
    status: 'flagged',
    details: 'Failed password attempt followed by unexpected password reset request.',
    endpoint: '/api/v1/auth/login',
    metadata: { failureReason: 'BAD_PASSWORD' }
  },
  {
    id: 'evt-119',
    timestamp: hoursAgo(14.5),
    type: 'login_success',
    severity: 'info',
    username: 'support_lead',
    ip: '109.201.152.12',
    location: { country: 'France', countryCode: 'FR', city: 'Paris', lat: 48.8566, lng: 2.3522 },
    device: { browser: 'Safari 17.0', os: 'macOS 14.1', userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)', isVpnOrTor: false },
    status: 'allowed',
    details: 'Password reset completed via verified company email link.',
    endpoint: '/api/v1/auth/reset-password',
    metadata: { tokenAgeMinutes: 4 }
  },
  {
    id: 'evt-120',
    timestamp: hoursAgo(18),
    type: 'login_failed',
    severity: 'high',
    username: 'postgres_admin',
    ip: '194.26.29.112',
    location: { country: 'Netherlands', countryCode: 'NL', city: 'Amsterdam', lat: 52.3676, lng: 4.9041 },
    device: { browser: 'Python-urllib/3.9', os: 'Linux', userAgent: 'Python-urllib/3.9', isVpnOrTor: true },
    status: 'blocked',
    details: 'Direct database port injection probe detected by intrusion prevention system.',
    mitreTechnique: 'T1190 - Exploit Public-Facing Application',
    endpoint: 'postgresql://db-prod-replica:5432',
    metadata: { targetDb: 'production_customer_data', port: 5432 }
  }
];

export const INITIAL_ALERTS: SecurityAlert[] = [
  {
    id: 'alt-901',
    ruleId: 'rule-impossible-travel',
    ruleName: 'Impossible Geolocation Velocity',
    severity: 'critical',
    status: 'active',
    detectedAt: minutesAgo(9),
    targetUser: 'maria.gonzalez@company.internal',
    targetIp: '103.249.23.4',
    summary: 'Account used to authenticate in Singapore only 18 minutes after prior authenticated session in Austin, Texas. Implies credential theft or compromised session token.',
    mitreTechnique: 'T1078.004 - Cloud Valid Accounts',
    eventCount: 2,
    associatedEventIds: ['evt-104', 'evt-115'],
    remediation: 'Immediately revoke active OAuth tokens, force password reset with MFA re-enrollment, and verify endpoint integrity.'
  },
  {
    id: 'alt-902',
    ruleId: 'rule-brute-force',
    ruleName: 'High-Frequency Brute Force Detection',
    severity: 'critical',
    status: 'active',
    detectedAt: minutesAgo(3),
    targetUser: 'admin',
    targetIp: '194.26.29.112',
    summary: 'Automated script attempted 7 invalid password combinations within 3 minutes targeting system administrator credentials.',
    mitreTechnique: 'T1110.001 - Password Guessing',
    eventCount: 7,
    associatedEventIds: ['evt-101', 'evt-102', 'evt-120'],
    remediation: 'Perimeter firewall auto-block rule triggered. Recommend validating that administrative portal is not exposed to public WAN without VPN.'
  },
  {
    id: 'alt-903',
    ruleId: 'rule-privilege-escalation',
    ruleName: 'Unauthorized Administrative Endpoint Probe',
    severity: 'high',
    status: 'investigating',
    detectedAt: minutesAgo(12),
    targetUser: 'contractor_temp04',
    targetIp: '82.165.197.1',
    summary: 'Temporary contractor account attempted to hit /api/v1/system/grant-superuser via CLI curl without authorization.',
    mitreTechnique: 'T1068 - Exploitation for Privilege Escalation',
    eventCount: 1,
    associatedEventIds: ['evt-105'],
    remediation: 'Account contractor_temp04 session suspended pending manager security review.'
  },
  {
    id: 'alt-904',
    ruleId: 'rule-token-leak',
    ruleName: 'Secret Token Inadvertently Exposed',
    severity: 'high',
    status: 'resolved',
    detectedAt: hoursAgo(3.2),
    targetUser: 'devops_ci_runner',
    targetIp: '172.56.21.90',
    summary: 'Continuous integration job artifact contained active production API token in plain text logs.',
    mitreTechnique: 'T1552.001 - Credentials In Files',
    eventCount: 1,
    associatedEventIds: ['evt-113'],
    remediation: 'API key revoked immediately and regenerated with restricted principle of least privilege.',
    resolutionNotes: 'Key sec_live_99a8b1 invalidated across AWS Secrets Manager. Build step updated with secret masking filter.'
  }
];
